language: minimal
jobs:
  include:
    - stage: build
      script: docker build -t rasp-mod .
    - script: docker run --rm --privileged rasp-mod \
                bash -e -o pipefail -c \
                "chmod +x build.sh && ./build.sh"
