language: minimal

sudo: required

services:
  - docker

script:
  - docker build -t edwardotme/raspbian-customiser:$TRAVIS_BRANCH .
  # Run the Docker image to test
  - IMAGE_LINK=http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-10-11/2018-10-09-raspbian-stretch-lite.zip
  - cd test/
  - wget -nv $IMAGE_LINK
  - IMAGE_ZIP=$(basename $IMAGE_LINK)
  - unzip -o $IMAGE_ZIP
  - rm $IMAGE_ZIP
  - cd ..
  - docker run --privileged --rm
    -e SOURCE_IMAGE=/test/${IMAGE_ZIP%.zip}.img
    -e SCRIPT=/test/test.sh
    --mount source=test,destination=/test
    edwardotme/raspbian-customiser:$TRAVIS_BRANCH
  # Stop here if this fails
  - |
    if [ $? -ne 0 ]; then
      exit 1
    fi
  # If this is the master branch an the test passes, add the 'stable' tag and push to the registry
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      docker tag edwardotme/raspbian-customiser:$TRAVIS_BRANCH edwardotme/raspbian-customiser:stable
      docker push edwardotme/raspbian-customiser:stable
    fi
